jwt:
  secret: 413F442A472D4B6150645367566B59703373367639792442264529482B4D6251
  expiration: 86400000 # 1 day

spring:
  cloud:
    aws:
      s3:
        enabled: false
      region:
        static: sa-east-1

  application:
    bucket:
      name: kocherovv

  datasource:
    url: jdbc:postgresql://localhost:32768/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        current_session_context_class: thread
        format_sql: true
        show_sql: true
        default_schema: study_schema_spring
    open-in-view: false
  liquibase:
    default-schema: study_schema_spring

  security:
    oauth2:
      google:
        redirect-url: http://localhost:8080/api/v1/oauth2/google/callback

logging:
  level:
    root: INFO
  file:
    name: example.log
    path: /
